


## Loading and preprocessing the data
Unzip the data file, read it, and create a new data frame with dates in the proper format. Clean up by removing the unzipped file.

unzip("./activity.zip")
a <- read.csv("./activity.csv", header=TRUE, na.strings="NA")
a <- data.frame(steps=a$steps, date=as.Date(a$date), interval=a$interval)
unlink("./activity.csv")



## What is mean total number of steps taken per day?
For this part of the assignment, you can ignore the missing values in the dataset.

    Make a histogram of the total number of steps taken each day

Compute the total number of steps each day (NA values removed)
sum_data <- aggregate(activity$steps, by=list(activity$date), FUN=sum, na.rm=TRUE)

Rename the attributes
names(sum_data) <- c("date", "total")
The histogram is given by the following lines of code:

Compute the histogram of the total number of steps each day
hist(sum_data$total, 
     breaks=seq(from=0, to=25000, by=2500),
     col="blue", 
     xlab="Total number of steps", 
     ylim=c(0, 20), 
     main="Histogram of the total number of steps taken each day\n(NA removed)")

## What is the average daily activity pattern?


    Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

Clear the workspace
rm(sum_data)

Compute the means of steps accross all days for each interval
mean_data <- aggregate(activity$steps, 
                       by=list(activity$interval), 
                       FUN=mean, 
                       na.rm=TRUE)

Rename the attributes
names(mean_data) <- c("interval", "mean")

The time serie plot is created by the following lines of code

Compute the time series plot
plot(mean_data$interval,      mean_data$mean, 
     type="l", 
     col="blue", 
     lwd=2, 
     xlab="Interval [minutes]", 
     ylab="Average number of steps", 
     main="Time-series of the average number of steps per intervals\n(NA removed)")


    Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

We find the position of the maximum mean
max_pos <- which(mean_data$mean == max(mean_data$mean))

We lookup the value of interval at this position
max_interval <- mean_data[max_pos, 1]


The 5-minute interval that contains the maximum of steps, on average across all days, is 835.

## Imputing missing values

Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NA’s)

We use the trick that a TRUE boolean value is equivalent to 1 and a FALSE to 0.
NA_count <- sum(is.na(activity$steps))

The number of NA’s is 2304.

Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

Find the NA positions
na_pos <- which(is.na(activity$steps))

Create a vector of means
mean_vec <- rep(mean(activity$steps, na.rm=TRUE), times=length(na_pos))

We use the strategy to remplace each NA value by the mean of the steps attribute.

Create a new dataset that is equal to the original dataset but with the missing data filled in.

Replace the NAs by the means
activity[na_pos, "steps"] <- mean_vec


    Make a histogram of the total number of steps taken each day and calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

Compute the total number of steps each day (NA values removed)
sum_data <- aggregate(activity$steps, by=list(activity$date), FUN=sum)

Rename the attributes
names(sum_data) <- c("date", "total")

Compute the histogram of the total number of steps each day
hist(sum_data$total, 
     breaks=seq(from=0, to=25000, by=2500),
     col="blue", 
     xlab="Total number of steps", 
     ylim=c(0, 30), 
     main="Histogram of the total number of steps taken each day\n(NA replaced by mean value)")

The mean and median are computed like

mean(sum_data$total)
median(sum_data$total)

These formulas gives a mean and median of 10766 and 10766 respectively.

These values differ greatly from the estimates from the first part of the assignment. The impact of imputing the missing values is to have more data, hence to obtain a bigger mean and median value.

## Are there differences in activity patterns between weekdays and weekends?
For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.

    Create a new factor variable in the dataset with two levels - “weekdays” and “weekend” indicating whether a given date is a weekday or weekend day.

The new factor variable "daytype" was already in the activity data frame
head(activity)

         date weekday daytype interval   steps
## 1 2012-10-01  monday weekday        0 37.3826
## 2 2012-10-01  monday weekday        5 37.3826
## 3 2012-10-01  monday weekday       10 37.3826
## 4 2012-10-01  monday weekday       15 37.3826
## 5 2012-10-01  monday weekday       20 37.3826
## 6 2012-10-01  monday weekday       25 37.3826

    Make a panel plot containing a time series plot (i.e. type = "l") of the 5- minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

Clear the workspace
rm(sum_data)

Load the lattice graphical library
library(lattice)

Compute the average number of steps taken, averaged across all daytype variable
mean_data <- aggregate(activity$steps, 
                       by=list(activity$daytype, 
                               activity$weekday, activity$interval), mean)

Rename the attributes
names(mean_data) <- c("daytype", "weekday", "interval", "mean")

We display the first few rows of the mean_data data frame:

head(mean_data)

   daytype  weekday interval     mean
## 1 weekday   friday        0 8.307244
## 2 weekday   monday        0 9.418355
## 3 weekend saturday        0 4.672825
## 4 weekend   sunday        0 4.672825
## 5 weekday thursday        0 9.375844
## 6 weekday  tuesday        0 0.000000

The time series plot take the following form:

Compute the time serie plot
xyplot(mean ~ interval | daytype, mean_data, 
       type="l", 
       lwd=1, 
       xlab="Interval", 
       ylab="Number of steps", 
       layout=c(1,2))


